# Generated by Django 4.2.3 on 2023-08-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_material_productmaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.ManyToManyField(through='accounts.ProductMaterial', to='accounts.material'),
        ),
    ]
